apiVersion: v1
kind: Service
metadata:
  labels:
    app-name: testapp
    app-version: master-58eb4f1e
  name: testapp
spec:
  ports:
    - appProtocol: http
      name: debug
      port: 8001
      targetPort: 8001
    - appProtocol: http
      name: http
      port: 80
      targetPort: 8000
  selector:
    app-name: testapp
